package logic

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	enNames = map[string]string{
		"UA电压":   "UA电压",
		"UB电压":   "UB电压",
		"UC电压":   "UC电压",
		"UAB电压":  "UAB电压",
		"UBC电压":  "UBC电压",
		"UCA电压":  "UCA电压",
		"A相电流":   "A相电流",
		"B相电流":   "B相电流",
		"C相电流":   "C相电流",
		"A相有功":   "A相有功",
		"B相有功":   "B相有功",
		"C相有功":   "C相有功",
		"总有功功率":  "总有功功率",
		"A相无功":   "A相无功",
		"B相无功":   "B相无功",
		"C相无功":   "C相无功",
		"总无功功率":  "总无功功率",
		"A相视在":   "A相视在",
		"B相视在":   "B相视在",
		"C相视在":   "C相视在",
		"总视在功率":  "总视在功率",
		"A相功率因素": "A相功率因素",
		"B相功率因素": "B相功率因素",
		"C相功率因素": "C相功率因素",
		"总功率因素":  "总功率因素",
		"A相电压角度": "A相电压角度",
		"B相电压角度": "B相电压角度",
		"C相电压角度": "C相电压角度",
		"A相电流角度": "A相电流角度",
		"B相电流角度": "B相电流角度",
		"C相电流角度": "C相电流角度",
		"电压频率":   "电压频率",
		"正向有功电能": "正向有功电能",
		"反向有功电能": "反向有功电能",
		"正向无功电能": "正向无功电能",
		"反向无功电能": "反向无功电能",
		"总视在电度":  "总视在电度",
	}
	//AmmtersColumns .....
	AmmtersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "devid", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeString},
		{Name: "UA电压", Type: field.TypeFloat32, Nullable: true},
		{Name: "UB电压", Type: field.TypeFloat32, Nullable: true},
		{Name: "UC电压", Type: field.TypeFloat32, Nullable: true},
		{Name: "UAB电压", Type: field.TypeFloat32, Nullable: true},
		{Name: "UBC电压", Type: field.TypeFloat32, Nullable: true},
		{Name: "UCA电压", Type: field.TypeFloat32, Nullable: true},
		{Name: "A相电流", Type: field.TypeFloat32, Nullable: true},
		{Name: "B相电流", Type: field.TypeFloat32, Nullable: true},
		{Name: "C相电流", Type: field.TypeFloat32, Nullable: true},
		{Name: "A相有功", Type: field.TypeFloat32, Nullable: true},
		{Name: "B相有功", Type: field.TypeFloat32, Nullable: true},
		{Name: "C相有功", Type: field.TypeFloat32, Nullable: true},
		{Name: "总有功功率", Type: field.TypeFloat32, Nullable: true},
		{Name: "A相无功", Type: field.TypeFloat32, Nullable: true},
		{Name: "B相无功", Type: field.TypeFloat32, Nullable: true},
		{Name: "C相无功", Type: field.TypeFloat32, Nullable: true},
		{Name: "总无功功率", Type: field.TypeFloat32, Nullable: true},
		{Name: "A相视在", Type: field.TypeFloat32, Nullable: true},
		{Name: "B相视在", Type: field.TypeFloat32, Nullable: true},
		{Name: "C相视在", Type: field.TypeFloat32, Nullable: true},
		{Name: "总视在功率", Type: field.TypeFloat32, Nullable: true},
		{Name: "A相功率因素", Type: field.TypeFloat32, Nullable: true},
		{Name: "B相功率因素", Type: field.TypeFloat32, Nullable: true},
		{Name: "C相功率因素", Type: field.TypeFloat32, Nullable: true},
		{Name: "总功率因素", Type: field.TypeFloat32, Nullable: true},
		{Name: "A相电压角度", Type: field.TypeFloat32, Nullable: true},
		{Name: "B相电压角度", Type: field.TypeFloat32, Nullable: true},
		{Name: "C相电压角度", Type: field.TypeFloat32, Nullable: true},
		{Name: "A相电流角度", Type: field.TypeFloat32, Nullable: true},
		{Name: "B相电流角度", Type: field.TypeFloat32, Nullable: true},
		{Name: "C相电流角度", Type: field.TypeFloat32, Nullable: true},
		{Name: "电压频率", Type: field.TypeFloat32, Nullable: true},
		{Name: "正向有功电能", Type: field.TypeFloat32, Nullable: true},
		{Name: "反向有功电能", Type: field.TypeFloat32, Nullable: true},
		{Name: "正向无功电能", Type: field.TypeFloat32, Nullable: true},
		{Name: "反向无功电能", Type: field.TypeFloat32, Nullable: true},
		{Name: "总视在电度", Type: field.TypeFloat32, Nullable: true},
	}
	// AmmtersTable holds the schema information for the "gateways" table.
	AmmtersTable = &schema.Table{
		Name:       "ammeters",
		Columns:    AmmtersColumns,
		PrimaryKey: []*schema.Column{AmmtersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ammter_devid",
				Unique:  true,
				Columns: []*schema.Column{AmmtersColumns[3]},
			},
		},
	}
	myTables = []*schema.Table{AmmtersTable}
)
