// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/yjiong/iotdor/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
