version: '3'
services:
  base:
    build:
      context: ./
      dockerfile: ./baseDockerfile
    image: base
  iotdor:
    build:
      context: ../
      dockerfile: ./docker/iotdorDockerfile
    restart: always
    image: iotdor
    container_name: iotdor
    depends_on:
      - mosquitto
      - mysql
      - redis
    links:
      - mosquitto
      - mysql
      - redis
    environment:
      SERVER_PORT: 8888
    ports:
      - "8888:8888"
    volumes:
      - "/etc/iotdor:/etc/iotdor"
      - "/var/iotdor/log:/iot/log"

  mosquitto:
    build:
      context: ./
      dockerfile: ./mqttDockerfile
    restart: always
    image: mosquittoiot
    container_name: mosquittoiot
    ports:
        - "1883:1883"
    environment:
      USER: yj
      PASSWORD: yj12345
      TZ: Asia/Shanghai

  mysql:
    build:
      context: ./
      dockerfile: ./mysqlDockerfile
    restart: always
    image: mysqliot
    container_name: mysqliot
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: iotdor
      MYSQL_USER: root
      MYSQL_PASSWORD: yaojiong
    volumes:
      - "/var/lib/mysql/:/var/lib/mysql"
      - "/var/run/mysqld:/run/mysqld"

  redis:
    build:
      context: ./
      dockerfile: ./redisDockerfile
    restart: always
    image: redisiot
    container_name: redisiot
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: yaojiong
    volumes:
      - "/var/lib/redis/:/var/lib/redis"

