broker:
  url: mqtt.yaojiong.top:1883
  username: yj
  password: yj12345
  keepalive: 60
  #publish qos
  pqos: 1
  #subscribe qos
  sqos: 1
  retain: false
  cafile:
  certfile:
  keyfile:
  iotdname: iotd-test
database:
  type: postgres 
  host: mqtt.yaojiong.top
  port: 5432
  user: iotd
  dbname: iotd
  password: yaojiong
  #interval x minutes storage 
  storage_interval: 5
redis:
  host: mqtt.yaojiong.top
  port: 46379
  password: yaojiong
http_server:
  port: 8888
  cert: server.cert
  key: server.key
  debug_flag: true
  

  


