broker:
  url: mqtt.yaojiong.top:1883
  username: yj
  password: yj12345
  keepalive: 60
  #publish qos
  pqos: 1
  #subscribe qos
  sqos: 1
  retain: false
  cafile:
  certfile:
  keyfile:
  iotdname: iotd-test
database:
  db: postgres 
  host: mqtt.yaojiong.top
  port: 5432
  user: iotd
  dbname: iotd
  password: yaojiong
redis:
  host: mqtt.yaojiong.top
  port: 56379
  password: yaojiong

  


