brokers: 
- url: mqtt.yaojiong.top:1883
  username: yj
  password: yj12345
  keepalive: 60
  qos: 1
  retain: false
  cafile:
  certfile:
  keyfile:
- url: iot.yaojiong.top:1883
  username: yj
  password: yj12345
  keepalive: 60
  qos: 1
  retain: false
  cafile:
  certfile:
  keyfile:
database:
  db: postgres 
  host: mqtt.yaojiong.top
  port: 5432
  user: iotd
  dbname: iotd
  password: yaojiong
  


