// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yjiong/iotdor/ent/device"
	"github.com/yjiong/iotdor/ent/gateway"
	"github.com/yjiong/iotdor/ent/organizationposition"
	"github.com/yjiong/iotdor/ent/predicate"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (du *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetUpdateTime sets the "update_time" field.
func (du *DeviceUpdate) SetUpdateTime(t time.Time) *DeviceUpdate {
	du.mutation.SetUpdateTime(t)
	return du
}

// SetDevID sets the "dev_id" field.
func (du *DeviceUpdate) SetDevID(s string) *DeviceUpdate {
	du.mutation.SetDevID(s)
	return du
}

// SetType sets the "type" field.
func (du *DeviceUpdate) SetType(s string) *DeviceUpdate {
	du.mutation.SetType(s)
	return du
}

// SetConn sets the "conn" field.
func (du *DeviceUpdate) SetConn(m map[string]interface{}) *DeviceUpdate {
	du.mutation.SetConn(m)
	return du
}

// SetReadInterval sets the "read_interval" field.
func (du *DeviceUpdate) SetReadInterval(i int) *DeviceUpdate {
	du.mutation.ResetReadInterval()
	du.mutation.SetReadInterval(i)
	return du
}

// SetNillableReadInterval sets the "read_interval" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableReadInterval(i *int) *DeviceUpdate {
	if i != nil {
		du.SetReadInterval(*i)
	}
	return du
}

// AddReadInterval adds i to the "read_interval" field.
func (du *DeviceUpdate) AddReadInterval(i int) *DeviceUpdate {
	du.mutation.AddReadInterval(i)
	return du
}

// ClearReadInterval clears the value of the "read_interval" field.
func (du *DeviceUpdate) ClearReadInterval() *DeviceUpdate {
	du.mutation.ClearReadInterval()
	return du
}

// SetStoreInterval sets the "store_interval" field.
func (du *DeviceUpdate) SetStoreInterval(i int) *DeviceUpdate {
	du.mutation.ResetStoreInterval()
	du.mutation.SetStoreInterval(i)
	return du
}

// SetNillableStoreInterval sets the "store_interval" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableStoreInterval(i *int) *DeviceUpdate {
	if i != nil {
		du.SetStoreInterval(*i)
	}
	return du
}

// AddStoreInterval adds i to the "store_interval" field.
func (du *DeviceUpdate) AddStoreInterval(i int) *DeviceUpdate {
	du.mutation.AddStoreInterval(i)
	return du
}

// ClearStoreInterval clears the value of the "store_interval" field.
func (du *DeviceUpdate) ClearStoreInterval() *DeviceUpdate {
	du.mutation.ClearStoreInterval()
	return du
}

// SetName sets the "name" field.
func (du *DeviceUpdate) SetName(s string) *DeviceUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableName(s *string) *DeviceUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// ClearName clears the value of the "name" field.
func (du *DeviceUpdate) ClearName() *DeviceUpdate {
	du.mutation.ClearName()
	return du
}

// SetDeleteFlag sets the "delete_flag" field.
func (du *DeviceUpdate) SetDeleteFlag(b bool) *DeviceUpdate {
	du.mutation.SetDeleteFlag(b)
	return du
}

// SetNillableDeleteFlag sets the "delete_flag" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableDeleteFlag(b *bool) *DeviceUpdate {
	if b != nil {
		du.SetDeleteFlag(*b)
	}
	return du
}

// ClearDeleteFlag clears the value of the "delete_flag" field.
func (du *DeviceUpdate) ClearDeleteFlag() *DeviceUpdate {
	du.mutation.ClearDeleteFlag()
	return du
}

// SetSummary sets the "summary" field.
func (du *DeviceUpdate) SetSummary(s string) *DeviceUpdate {
	du.mutation.SetSummary(s)
	return du
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (du *DeviceUpdate) SetNillableSummary(s *string) *DeviceUpdate {
	if s != nil {
		du.SetSummary(*s)
	}
	return du
}

// ClearSummary clears the value of the "summary" field.
func (du *DeviceUpdate) ClearSummary() *DeviceUpdate {
	du.mutation.ClearSummary()
	return du
}

// SetOrganizationPositionID sets the "organization_position" edge to the OrganizationPosition entity by ID.
func (du *DeviceUpdate) SetOrganizationPositionID(id int) *DeviceUpdate {
	du.mutation.SetOrganizationPositionID(id)
	return du
}

// SetNillableOrganizationPositionID sets the "organization_position" edge to the OrganizationPosition entity by ID if the given value is not nil.
func (du *DeviceUpdate) SetNillableOrganizationPositionID(id *int) *DeviceUpdate {
	if id != nil {
		du = du.SetOrganizationPositionID(*id)
	}
	return du
}

// SetOrganizationPosition sets the "organization_position" edge to the OrganizationPosition entity.
func (du *DeviceUpdate) SetOrganizationPosition(o *OrganizationPosition) *DeviceUpdate {
	return du.SetOrganizationPositionID(o.ID)
}

// SetGatewayID sets the "gateway" edge to the Gateway entity by ID.
func (du *DeviceUpdate) SetGatewayID(id int) *DeviceUpdate {
	du.mutation.SetGatewayID(id)
	return du
}

// SetNillableGatewayID sets the "gateway" edge to the Gateway entity by ID if the given value is not nil.
func (du *DeviceUpdate) SetNillableGatewayID(id *int) *DeviceUpdate {
	if id != nil {
		du = du.SetGatewayID(*id)
	}
	return du
}

// SetGateway sets the "gateway" edge to the Gateway entity.
func (du *DeviceUpdate) SetGateway(g *Gateway) *DeviceUpdate {
	return du.SetGatewayID(g.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (du *DeviceUpdate) Mutation() *DeviceMutation {
	return du.mutation
}

// ClearOrganizationPosition clears the "organization_position" edge to the OrganizationPosition entity.
func (du *DeviceUpdate) ClearOrganizationPosition() *DeviceUpdate {
	du.mutation.ClearOrganizationPosition()
	return du
}

// ClearGateway clears the "gateway" edge to the Gateway entity.
func (du *DeviceUpdate) ClearGateway() *DeviceUpdate {
	du.mutation.ClearGateway()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DeviceUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	du.defaults()
	if len(du.hooks) == 0 {
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeviceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			if du.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DeviceUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (du *DeviceUpdate) defaults() {
	if _, ok := du.mutation.UpdateTime(); !ok {
		v := device.UpdateDefaultUpdateTime()
		du.mutation.SetUpdateTime(v)
	}
}

func (du *DeviceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   device.Table,
			Columns: device.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: device.FieldID,
			},
		},
	}
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: device.FieldUpdateTime,
		})
	}
	if value, ok := du.mutation.DevID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldDevID,
		})
	}
	if value, ok := du.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldType,
		})
	}
	if value, ok := du.mutation.Conn(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: device.FieldConn,
		})
	}
	if value, ok := du.mutation.ReadInterval(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldReadInterval,
		})
	}
	if value, ok := du.mutation.AddedReadInterval(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldReadInterval,
		})
	}
	if du.mutation.ReadIntervalCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: device.FieldReadInterval,
		})
	}
	if value, ok := du.mutation.StoreInterval(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldStoreInterval,
		})
	}
	if value, ok := du.mutation.AddedStoreInterval(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldStoreInterval,
		})
	}
	if du.mutation.StoreIntervalCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: device.FieldStoreInterval,
		})
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldName,
		})
	}
	if du.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldName,
		})
	}
	if value, ok := du.mutation.DeleteFlag(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: device.FieldDeleteFlag,
		})
	}
	if du.mutation.DeleteFlagCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: device.FieldDeleteFlag,
		})
	}
	if value, ok := du.mutation.Summary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldSummary,
		})
	}
	if du.mutation.SummaryCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldSummary,
		})
	}
	if du.mutation.OrganizationPositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.OrganizationPositionTable,
			Columns: []string{device.OrganizationPositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: organizationposition.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.OrganizationPositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.OrganizationPositionTable,
			Columns: []string{device.OrganizationPositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: organizationposition.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if du.mutation.GatewayCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.GatewayTable,
			Columns: []string{device.GatewayColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gateway.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.GatewayIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.GatewayTable,
			Columns: []string{device.GatewayColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gateway.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetUpdateTime sets the "update_time" field.
func (duo *DeviceUpdateOne) SetUpdateTime(t time.Time) *DeviceUpdateOne {
	duo.mutation.SetUpdateTime(t)
	return duo
}

// SetDevID sets the "dev_id" field.
func (duo *DeviceUpdateOne) SetDevID(s string) *DeviceUpdateOne {
	duo.mutation.SetDevID(s)
	return duo
}

// SetType sets the "type" field.
func (duo *DeviceUpdateOne) SetType(s string) *DeviceUpdateOne {
	duo.mutation.SetType(s)
	return duo
}

// SetConn sets the "conn" field.
func (duo *DeviceUpdateOne) SetConn(m map[string]interface{}) *DeviceUpdateOne {
	duo.mutation.SetConn(m)
	return duo
}

// SetReadInterval sets the "read_interval" field.
func (duo *DeviceUpdateOne) SetReadInterval(i int) *DeviceUpdateOne {
	duo.mutation.ResetReadInterval()
	duo.mutation.SetReadInterval(i)
	return duo
}

// SetNillableReadInterval sets the "read_interval" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableReadInterval(i *int) *DeviceUpdateOne {
	if i != nil {
		duo.SetReadInterval(*i)
	}
	return duo
}

// AddReadInterval adds i to the "read_interval" field.
func (duo *DeviceUpdateOne) AddReadInterval(i int) *DeviceUpdateOne {
	duo.mutation.AddReadInterval(i)
	return duo
}

// ClearReadInterval clears the value of the "read_interval" field.
func (duo *DeviceUpdateOne) ClearReadInterval() *DeviceUpdateOne {
	duo.mutation.ClearReadInterval()
	return duo
}

// SetStoreInterval sets the "store_interval" field.
func (duo *DeviceUpdateOne) SetStoreInterval(i int) *DeviceUpdateOne {
	duo.mutation.ResetStoreInterval()
	duo.mutation.SetStoreInterval(i)
	return duo
}

// SetNillableStoreInterval sets the "store_interval" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableStoreInterval(i *int) *DeviceUpdateOne {
	if i != nil {
		duo.SetStoreInterval(*i)
	}
	return duo
}

// AddStoreInterval adds i to the "store_interval" field.
func (duo *DeviceUpdateOne) AddStoreInterval(i int) *DeviceUpdateOne {
	duo.mutation.AddStoreInterval(i)
	return duo
}

// ClearStoreInterval clears the value of the "store_interval" field.
func (duo *DeviceUpdateOne) ClearStoreInterval() *DeviceUpdateOne {
	duo.mutation.ClearStoreInterval()
	return duo
}

// SetName sets the "name" field.
func (duo *DeviceUpdateOne) SetName(s string) *DeviceUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableName(s *string) *DeviceUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// ClearName clears the value of the "name" field.
func (duo *DeviceUpdateOne) ClearName() *DeviceUpdateOne {
	duo.mutation.ClearName()
	return duo
}

// SetDeleteFlag sets the "delete_flag" field.
func (duo *DeviceUpdateOne) SetDeleteFlag(b bool) *DeviceUpdateOne {
	duo.mutation.SetDeleteFlag(b)
	return duo
}

// SetNillableDeleteFlag sets the "delete_flag" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableDeleteFlag(b *bool) *DeviceUpdateOne {
	if b != nil {
		duo.SetDeleteFlag(*b)
	}
	return duo
}

// ClearDeleteFlag clears the value of the "delete_flag" field.
func (duo *DeviceUpdateOne) ClearDeleteFlag() *DeviceUpdateOne {
	duo.mutation.ClearDeleteFlag()
	return duo
}

// SetSummary sets the "summary" field.
func (duo *DeviceUpdateOne) SetSummary(s string) *DeviceUpdateOne {
	duo.mutation.SetSummary(s)
	return duo
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableSummary(s *string) *DeviceUpdateOne {
	if s != nil {
		duo.SetSummary(*s)
	}
	return duo
}

// ClearSummary clears the value of the "summary" field.
func (duo *DeviceUpdateOne) ClearSummary() *DeviceUpdateOne {
	duo.mutation.ClearSummary()
	return duo
}

// SetOrganizationPositionID sets the "organization_position" edge to the OrganizationPosition entity by ID.
func (duo *DeviceUpdateOne) SetOrganizationPositionID(id int) *DeviceUpdateOne {
	duo.mutation.SetOrganizationPositionID(id)
	return duo
}

// SetNillableOrganizationPositionID sets the "organization_position" edge to the OrganizationPosition entity by ID if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableOrganizationPositionID(id *int) *DeviceUpdateOne {
	if id != nil {
		duo = duo.SetOrganizationPositionID(*id)
	}
	return duo
}

// SetOrganizationPosition sets the "organization_position" edge to the OrganizationPosition entity.
func (duo *DeviceUpdateOne) SetOrganizationPosition(o *OrganizationPosition) *DeviceUpdateOne {
	return duo.SetOrganizationPositionID(o.ID)
}

// SetGatewayID sets the "gateway" edge to the Gateway entity by ID.
func (duo *DeviceUpdateOne) SetGatewayID(id int) *DeviceUpdateOne {
	duo.mutation.SetGatewayID(id)
	return duo
}

// SetNillableGatewayID sets the "gateway" edge to the Gateway entity by ID if the given value is not nil.
func (duo *DeviceUpdateOne) SetNillableGatewayID(id *int) *DeviceUpdateOne {
	if id != nil {
		duo = duo.SetGatewayID(*id)
	}
	return duo
}

// SetGateway sets the "gateway" edge to the Gateway entity.
func (duo *DeviceUpdateOne) SetGateway(g *Gateway) *DeviceUpdateOne {
	return duo.SetGatewayID(g.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (duo *DeviceUpdateOne) Mutation() *DeviceMutation {
	return duo.mutation
}

// ClearOrganizationPosition clears the "organization_position" edge to the OrganizationPosition entity.
func (duo *DeviceUpdateOne) ClearOrganizationPosition() *DeviceUpdateOne {
	duo.mutation.ClearOrganizationPosition()
	return duo
}

// ClearGateway clears the "gateway" edge to the Gateway entity.
func (duo *DeviceUpdateOne) ClearGateway() *DeviceUpdateOne {
	duo.mutation.ClearGateway()
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Device entity.
func (duo *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	var (
		err  error
		node *Device
	)
	duo.defaults()
	if len(duo.hooks) == 0 {
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeviceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			if duo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = duo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, duo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Device)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from DeviceMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (duo *DeviceUpdateOne) defaults() {
	if _, ok := duo.mutation.UpdateTime(); !ok {
		v := device.UpdateDefaultUpdateTime()
		duo.mutation.SetUpdateTime(v)
	}
}

func (duo *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   device.Table,
			Columns: device.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: device.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: device.FieldUpdateTime,
		})
	}
	if value, ok := duo.mutation.DevID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldDevID,
		})
	}
	if value, ok := duo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldType,
		})
	}
	if value, ok := duo.mutation.Conn(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: device.FieldConn,
		})
	}
	if value, ok := duo.mutation.ReadInterval(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldReadInterval,
		})
	}
	if value, ok := duo.mutation.AddedReadInterval(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldReadInterval,
		})
	}
	if duo.mutation.ReadIntervalCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: device.FieldReadInterval,
		})
	}
	if value, ok := duo.mutation.StoreInterval(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldStoreInterval,
		})
	}
	if value, ok := duo.mutation.AddedStoreInterval(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: device.FieldStoreInterval,
		})
	}
	if duo.mutation.StoreIntervalCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: device.FieldStoreInterval,
		})
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldName,
		})
	}
	if duo.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldName,
		})
	}
	if value, ok := duo.mutation.DeleteFlag(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: device.FieldDeleteFlag,
		})
	}
	if duo.mutation.DeleteFlagCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: device.FieldDeleteFlag,
		})
	}
	if value, ok := duo.mutation.Summary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: device.FieldSummary,
		})
	}
	if duo.mutation.SummaryCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: device.FieldSummary,
		})
	}
	if duo.mutation.OrganizationPositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.OrganizationPositionTable,
			Columns: []string{device.OrganizationPositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: organizationposition.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.OrganizationPositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.OrganizationPositionTable,
			Columns: []string{device.OrganizationPositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: organizationposition.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if duo.mutation.GatewayCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.GatewayTable,
			Columns: []string{device.GatewayColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gateway.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.GatewayIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.GatewayTable,
			Columns: []string{device.GatewayColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gateway.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Device{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
